<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tai Yu Ying">
<meta name="dcterms.date" content="2024-10-21">

<title>Take-home Exercise 3.2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../Take-home_Ex03/Take-homeExercise3.1.html"> 
<span class="menu-text">Take-home Exercise 3.1</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../Take-home_Ex03/Take-homeExercise3.2.html" aria-current="page"> 
<span class="menu-text">Take-home Exercise 3.2</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#data-upload-and-initial-setup" id="toc-data-upload-and-initial-setup" class="nav-link active" data-scroll-target="#data-upload-and-initial-setup"><span class="header-section-number">1</span> Data Upload and Initial Setup</a>
  <ul class="collapse">
  <li><a href="#installing-and-launching-the-r-packages" id="toc-installing-and-launching-the-r-packages" class="nav-link" data-scroll-target="#installing-and-launching-the-r-packages"><span class="header-section-number">1.1</span> Installing and launching the R packages</a></li>
  </ul></li>
  <li><a href="#building-random-forest-model" id="toc-building-random-forest-model" class="nav-link" data-scroll-target="#building-random-forest-model"><span class="header-section-number">2</span> Building Random Forest Model</a>
  <ul class="collapse">
  <li><a href="#data-sampling" id="toc-data-sampling" class="nav-link" data-scroll-target="#data-sampling"><span class="header-section-number">2.1</span> Data Sampling</a></li>
  <li><a href="#preparing-coordinates-data" id="toc-preparing-coordinates-data" class="nav-link" data-scroll-target="#preparing-coordinates-data"><span class="header-section-number">2.2</span> Preparing coordinates data</a></li>
  <li><a href="#calibrating-random-forest-model" id="toc-calibrating-random-forest-model" class="nav-link" data-scroll-target="#calibrating-random-forest-model"><span class="header-section-number">2.3</span> Calibrating Random Forest Model</a></li>
  <li><a href="#key-insights" id="toc-key-insights" class="nav-link" data-scroll-target="#key-insights"><span class="header-section-number">2.4</span> Key Insights:</a></li>
  </ul></li>
  <li><a href="#calibrating-gwr-predictive-method" id="toc-calibrating-gwr-predictive-method" class="nav-link" data-scroll-target="#calibrating-gwr-predictive-method"><span class="header-section-number">3</span> Calibrating gwr predictive method</a>
  <ul class="collapse">
  <li><a href="#data-sampling-1" id="toc-data-sampling-1" class="nav-link" data-scroll-target="#data-sampling-1"><span class="header-section-number">3.1</span> Data Sampling</a></li>
  <li><a href="#converting-the-sf-data.frame-to-spatialpointdataframe" id="toc-converting-the-sf-data.frame-to-spatialpointdataframe" class="nav-link" data-scroll-target="#converting-the-sf-data.frame-to-spatialpointdataframe"><span class="header-section-number">3.2</span> Converting the sf data.frame to SpatialPointDataFrame</a></li>
  <li><a href="#computing-adaptive-bandwidth" id="toc-computing-adaptive-bandwidth" class="nav-link" data-scroll-target="#computing-adaptive-bandwidth"><span class="header-section-number">3.3</span> Computing adaptive bandwidth</a></li>
  <li><a href="#constructing-the-adaptive-bandwidth-gwr-model" id="toc-constructing-the-adaptive-bandwidth-gwr-model" class="nav-link" data-scroll-target="#constructing-the-adaptive-bandwidth-gwr-model"><span class="header-section-number">3.4</span> Constructing the adaptive bandwidth gwr model</a></li>
  <li><a href="#retrieve-gwr-output-object" id="toc-retrieve-gwr-output-object" class="nav-link" data-scroll-target="#retrieve-gwr-output-object"><span class="header-section-number">3.5</span> Retrieve gwr output object</a></li>
  <li><a href="#converting-the-test-data-from-sf-data.frame-to-spatialpointdataframe" id="toc-converting-the-test-data-from-sf-data.frame-to-spatialpointdataframe" class="nav-link" data-scroll-target="#converting-the-test-data-from-sf-data.frame-to-spatialpointdataframe"><span class="header-section-number">3.6</span> Converting the test data from sf data.frame to SpatialPointDataFrame</a></li>
  <li><a href="#computing-predicted-values-of-the-test-data" id="toc-computing-predicted-values-of-the-test-data" class="nav-link" data-scroll-target="#computing-predicted-values-of-the-test-data"><span class="header-section-number">3.7</span> Computing predicted values of the test data</a></li>
  <li><a href="#key-takeaways" id="toc-key-takeaways" class="nav-link" data-scroll-target="#key-takeaways"><span class="header-section-number">3.8</span> Key Takeaways</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home Exercise 3.2</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tai Yu Ying </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 21, 2024</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">November 12, 2024</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="data-upload-and-initial-setup" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="data-upload-and-initial-setup"><span class="header-section-number">1</span> Data Upload and Initial Setup</h2>
<section id="installing-and-launching-the-r-packages" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="installing-and-launching-the-r-packages"><span class="header-section-number">1.1</span> Installing and launching the R packages</h3>
<p>In this exercise, the following R packages will be used, they are:</p>
<ul>
<li><strong>tidyverse</strong>: A collection of R packages (including <code>dplyr</code>, <code>ggplot2</code>, <code>tidyr</code>, and more) for data manipulation, visualization, and cleaning. It is essential for streamlined data handling and is widely used for data wrangling and efficient manipulation of data frames.</li>
<li><strong>sf (Simple Features)</strong>: A package that provides a standard approach for handling spatial data, such as shapefiles and geographic coordinates, in R. It’s useful for transforming data into spatial formats and performing spatial operations.</li>
<li><strong>httr</strong>: Facilitates HTTP requests, enabling access to external APIs to fetch locational or additional data about amenities or other contextual factors that may influence housing prices.</li>
<li><strong>jsonlite</strong>: A package used for parsing JSON data, often encountered in web APIs. This package is useful for converting JSON data into R data structures, allowing for seamless integration of JSON-formatted locational or contextual data.</li>
<li><strong>rvest</strong>: Supports web scraping, making it easy to extract data from websites. This can be useful if additional information from web sources (such as lists of nearby amenities or environmental factors) is required for analysis.</li>
<li><strong>tmap</strong>: A powerful package for creating static and interactive thematic maps. It’s helpful for visualizing spatial patterns, clusters, and trends in housing prices or other variables across geographic areas.</li>
<li><strong>leaflet</strong>: A mapping package focused on interactive maps. It is useful for creating dynamic spatial visualizations, which can help communicate results effectively to stakeholders.</li>
<li><strong>ggstatsplot</strong>: An extension of <code>ggplot2</code> for enhanced statistical visualizations, adding statistical information and context to graphs. It’s useful for presenting both spatial and non-spatial relationships within the dataset.</li>
<li><strong>spdep</strong>: Used for spatial dependency analysis, <code>spdep</code> provides tools for calculating spatial autocorrelation (e.g., Moran’s I) and creating spatial weights, essential for analyzing spatial relationships among housing prices or other spatial data points.</li>
<li><strong>spgwr</strong>: Implements Geographically Weighted Regression (GWR) in R. This is useful for local regression analyses that reveal spatial variations in relationships, such as the effect of locational and structural factors on housing prices.</li>
<li><strong>olsrr</strong>: A package for ordinary least squares (OLS) regression diagnostics, which can aid in assessing model assumptions, identifying influential observations, and evaluating model performance.</li>
<li><strong>gtsummary</strong>: Provides summary tables and statistics in a clean format, making it easy to generate quick overviews of data or model outputs. Useful for generating reports with organized statistical summaries.</li>
<li><strong>GWmodel</strong>: A specialized package for geographically weighted models, including Geographically Weighted Random Forests (GWRF), which are advanced models that capture complex spatial patterns in data.</li>
<li><strong>rsample</strong>: A package for creating resampling objects, which is useful for cross-validation and other validation strategies to assess model performance on different subsets of data.</li>
<li><strong>ranger</strong>: An efficient implementation of the Random Forest algorithm in R, which can handle large datasets and be applied in predictive modeling tasks, including spatial modeling when combined with <code>GWmodel</code>.</li>
<li><strong>spatialML</strong>: Supports machine learning on spatial data, providing tools that are specifically designed to handle the unique characteristics of spatial data in predictive modeling.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse, sf, httr, jsonlite, rvest, tmap, leaflet, ggstatsplot, spdep, spgwr, olsrr, gtsummary, GWmodel, rsample, ranger, SpatialML)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="building-random-forest-model" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="building-random-forest-model"><span class="header-section-number">2</span> Building Random Forest Model</h2>
<section id="data-sampling" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="data-sampling"><span class="header-section-number">2.1</span> Data Sampling</h3>
<p>The entire data are split into training and test data sets with 65% and 35% respectively by using&nbsp;<em>initial_split()</em>&nbsp;of&nbsp;<strong>rsample</strong>&nbsp;package. rsample is one of the package of tigymodels.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>resale_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(resale_final, </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">prop =</span> <span class="fl">6.5</span><span class="sc">/</span><span class="dv">10</span>,)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> <span class="fu">training</span>(resale_split)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> <span class="fu">testing</span>(resale_split)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(train_data, <span class="st">"data/HDB/rds/train_data.rds"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(test_data, <span class="st">"data/HDB/rds/test_data.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/HDB/rds/train_data.rds"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/HDB/rds/test_data.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="preparing-coordinates-data" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="preparing-coordinates-data"><span class="header-section-number">2.2</span> Preparing coordinates data</h3>
<section id="extracting-coordinates-data" class="level4" data-number="2.2.1">
<h4 data-number="2.2.1" class="anchored" data-anchor-id="extracting-coordinates-data"><span class="header-section-number">2.2.1</span> Extracting coordinates data</h4>
<p>The code chunk below extract the x,y coordinates of the full, training and test data sets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(resale_final)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>coords_train <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(train_data)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>coords_test <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(test_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Before continue, we write all the output into rds for future used.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>coords_train <span class="ot">&lt;-</span> <span class="fu">write_rds</span>(coords_train, <span class="st">"data/HDB/rds/coords_train.rds"</span> )</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>coords_test <span class="ot">&lt;-</span> <span class="fu">write_rds</span>(coords_test, <span class="st">"data/HDB/rds/coords_test.rds"</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>coords_train <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/HDB/rds/coords_train.rds"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>coords_test <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/HDB/rds/coords_test.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="dropping-geometry-field" class="level4" data-number="2.2.2">
<h4 data-number="2.2.2" class="anchored" data-anchor-id="dropping-geometry-field"><span class="header-section-number">2.2.2</span> Dropping geometry field</h4>
<p>First, we will drop geometry column of the sf data.frame by using&nbsp;<code>st_drop_geometry()</code>&nbsp;of sf package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> train_data <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="calibrating-random-forest-model" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="calibrating-random-forest-model"><span class="header-section-number">2.3</span> Calibrating Random Forest Model</h3>
<p>We’ll calibrate a model to predict HDB resale price by using random forest function of&nbsp;<a href="https://cran.r-project.org/web/packages/ranger/index.html"><strong>ranger</strong></a>&nbsp;package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert columns to factors if they are not already</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>train_data<span class="sc">$</span>flat_type <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(train_data<span class="sc">$</span>flat_type)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>train_data<span class="sc">$</span>region <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(train_data<span class="sc">$</span>region)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>train_data<span class="sc">$</span>flat_model <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(train_data<span class="sc">$</span>flat_model)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the random forest model</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>rf <span class="ot">&lt;-</span> <span class="fu">ranger</span>(<span class="at">formula =</span> resale_price <span class="sc">~</span> </span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>                 floor_area_sqm <span class="sc">+</span> </span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>                 storey_avg <span class="sc">+</span> </span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>                 remaining_lease_total_mths <span class="sc">+</span> </span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>                 proximity_to_mrt <span class="sc">+</span> </span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>                 proximity_to_goodprisch <span class="sc">+</span> </span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>                 within_1km_prisch <span class="sc">+</span> </span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>                 proximity_to_eldercare <span class="sc">+</span> </span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>                 proximity_to_CHAS <span class="sc">+</span> </span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>                 proximity_to_spmrkt <span class="sc">+</span> </span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>                 proximity_to_hawker <span class="sc">+</span> </span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>                 proximity_to_parks <span class="sc">+</span> </span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>                 proximity_to_childcare <span class="sc">+</span> </span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>                 within_350m_childcare <span class="sc">+</span> </span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>                 proximity_to_busstop <span class="sc">+</span> </span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>                 within_350m_busstop <span class="sc">+</span> </span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>                 proximity_to_mall <span class="sc">+</span> </span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>                 flat_type <span class="sc">+</span> </span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>                 region <span class="sc">+</span> </span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>                 flat_model,  <span class="co"># Assuming 'flat_type', 'region'                  , and 'flat_model' are factors</span></span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> train_data</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(rf, <span class="st">"data/HDB/rds/rf.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>rf <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/HDB/rds/rf.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the model output</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>rf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>function (n, df1, df2, ncp) 
{
    if (missing(ncp)) 
        .Call(C_rf, n, df1, df2)
    else (rchisq(n, df1, ncp = ncp)/df1)/(rchisq(n, df2)/df2)
}
&lt;bytecode: 0x0000022fa31b0be0&gt;
&lt;environment: namespace:stats&gt;</code></pre>
</div>
</div>
</section>
<section id="key-insights" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="key-insights"><span class="header-section-number">2.4</span> Key Insights:</h3>
<ol type="1">
<li><p><strong>Call</strong>: This shows the formula and data used for the model. It confirms that <code>resale_price</code> is the dependent variable, and the other variables in the formula are predictors.</p></li>
<li><p><strong>Type</strong>: The model is a regression model, meaning it predicts a continuous outcome (resale price) based on the input features.</p></li>
<li><p><strong>Number of Trees</strong>: The model used 500 trees, which is typical for a random forest model to ensure stability and robustness in predictions.</p></li>
<li><p><strong>Sample Size</strong>: The model trained on 15,310 data points. This is the total number of observations in the training dataset after any preprocessing.</p></li>
<li><p><strong>Number of Independent Variables</strong>: There are 19 predictor variables used in the model. These include both numerical features (e.g., <code>floor_area_sqm</code>, <code>remaining_lease_total_mths</code>) and categorical features (e.g., <code>flat_type</code>, <code>region</code>, <code>flat_model</code>).</p></li>
<li><p><strong>Mtry</strong>: This is the number of variables randomly sampled as candidates at each split, set to 4 in this case. In regression, it’s generally recommended to set <code>mtry</code> to around the square root of the number of predictors, which the model has done here.</p></li>
<li><p><strong>Target Node Size</strong>: This is the minimum number of data points in a node before a split is attempted. A target node size of 5 indicates that the trees were allowed to grow fairly deep, capturing more nuances in the data.</p></li>
<li><p><strong>Variable Importance Mode</strong>: The model did not calculate variable importance metrics in this run (<code>none</code>). To get insights into which variables contribute most to the model, you could rerun the model with variable importance set to <code>impurity</code> or <code>permutation</code>.</p></li>
<li><p><strong>Out-of-Bag (OOB) Prediction Error (MSE)</strong>: The mean squared error (MSE) for the model based on out-of-bag samples (i.e., samples not used in each tree’s training) is about 135,242,786.4. This metric indicates the average squared difference between the predicted and actual values. A lower MSE indicates a better model fit. However, given that the actual resale prices could vary widely, the raw MSE value alone is less intuitive than its square root, which would give the average error in the same units as <code>resale_price</code>.</p></li>
<li><p><strong>Out-of-Bag R-Squared (OOB R²)</strong>: The OOB R² of 0.9481 indicates that approximately 94.8% of the variance in resale prices can be explained by this model. This is a high R² value, suggesting that the model fits the data well and that the predictors capture a significant portion of the variability in the resale prices.</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Summary
</div>
</div>
<div class="callout-body-container callout-body">
<p>The model explains a large portion of the variability in resale prices (OOB R² of 94.8%), which suggests that the selected predictors are well-suited for this task. However, the MSE suggests some degree of error in individual predictions, which is typical with high-dimensional and complex datasets. If you want to understand which variables contribute most to the predictions, consider recalculating the model with variable importance metrics enabled. This would allow you to identify the predictors with the most significant impact on resale prices and refine the model if needed.</p>
</div>
</div>
</section>
</section>
<section id="calibrating-gwr-predictive-method" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="calibrating-gwr-predictive-method"><span class="header-section-number">3</span> Calibrating gwr predictive method</h2>
<p>We’ll calibrate a model to predict HDB resale price by using geographically weighted regression method of&nbsp;<a href="https://cran.r-project.org/web/packages/GWmodel/index.html"><strong>GWmodel</strong></a>&nbsp;package.</p>
<p>Due to time constraint, we’ll select “West” region with “Standard” flats (an affordable segment) for our prediction model.</p>
<section id="data-sampling-1" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data-sampling-1"><span class="header-section-number">3.1</span> Data Sampling</h3>
<p>The entire data are split into training and test data sets with 65% and 35% respectively by using&nbsp;<em>initial_split()</em>&nbsp;of&nbsp;<strong>rsample</strong>&nbsp;package. rsample is one of the package of tigymodels.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>W_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(West_Simplified, </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">prop =</span> <span class="fl">6.5</span><span class="sc">/</span><span class="dv">10</span>,)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>Wtrain_data <span class="ot">&lt;-</span> <span class="fu">training</span>(W_split)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>Wtest_data <span class="ot">&lt;-</span> <span class="fu">testing</span>(W_split)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(Wtrain_data, <span class="st">"data/HDB/rds/Wtrain_data.rds"</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(Wtest_data, <span class="st">"data/HDB/rds/Wtest_data.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>Wtrain_data <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/HDB/rds/Wtrain_data.rds"</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>Wtest_data <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/HDB/rds/Wtest_data.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="converting-the-sf-data.frame-to-spatialpointdataframe" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="converting-the-sf-data.frame-to-spatialpointdataframe"><span class="header-section-number">3.2</span> Converting the sf data.frame to SpatialPointDataFrame</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>train_data_sp <span class="ot">&lt;-</span> <span class="fu">as_Spatial</span>(Wtrain_data)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>train_data_sp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatialPointsDataFrame 
features    : 53 
extent      : 15874.38, 21512.98, 33696.28, 40886.84  (xmin, xmax, ymin, ymax)
crs         : +proj=tmerc +lat_0=1.36666666666667 +lon_0=103.833333333333 +k=1 +x_0=28001.642 +y_0=38744.572 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
variables   : 21
names       : resale_price,        town, region, flat_type, flat_model, floor_area_sqm, storey_avg, remaining_lease_total_mths,  proximity_to_mrt, proximity_to_goodprisch, within_1km_prisch, proximity_to_eldercare,    proximity_to_CHAS, proximity_to_spmrkt, proximity_to_hawker, ... 
min values  :       393000, Bukit Batok,   West,    4 ROOM, Simplified,             83,          2,                        729, 0.109513324694062,       0.733705947485525,                 0,       0.14154563839911, 1.63444770069886e-08,  0.0398263831270178,   0.191639179549987, ... 
max values  :       480000, Jurong West,   West,    4 ROOM, Simplified,             89,         11,                        779,  1.39680251695794,         5.3465481705808,                 1,       2.41846152812648,    0.492061964279255,   0.622852294951817,    1.97345230639643, ... </code></pre>
</div>
</div>
</section>
<section id="computing-adaptive-bandwidth" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="computing-adaptive-bandwidth"><span class="header-section-number">3.3</span> Computing adaptive bandwidth</h3>
<p>Next,&nbsp;<code>bw.gwr()</code>&nbsp;of&nbsp;<strong>GWmodel</strong>&nbsp;package will be used to determine the optimal bandwidth to be used.</p>
<p>The code chunk below is used to determine adaptive bandwidth and CV method is used to determine the optimal bandwidth.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>bw_adaptive <span class="ot">&lt;-</span> <span class="fu">bw.gwr</span>(<span class="at">formula =</span> resale_price <span class="sc">~</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>                 floor_area_sqm <span class="sc">+</span> </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>                 storey_avg <span class="sc">+</span> </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>                 remaining_lease_total_mths <span class="sc">+</span> </span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>                 proximity_to_mrt <span class="sc">+</span> </span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>                 proximity_to_goodprisch <span class="sc">+</span> </span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>                 within_1km_prisch <span class="sc">+</span> </span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>                 proximity_to_eldercare <span class="sc">+</span> </span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>                 proximity_to_CHAS <span class="sc">+</span> </span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>                 proximity_to_spmrkt <span class="sc">+</span> </span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>                 proximity_to_hawker <span class="sc">+</span> </span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>                 proximity_to_parks <span class="sc">+</span> </span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>                 proximity_to_childcare <span class="sc">+</span> </span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>                 within_350m_childcare <span class="sc">+</span> </span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>                 proximity_to_busstop <span class="sc">+</span> </span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>                 within_350m_busstop <span class="sc">+</span> </span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>                 proximity_to_mall,</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data=</span>train_data_sp,</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>                 <span class="at">approach=</span><span class="st">"CV"</span>,</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>                 <span class="at">kernel=</span><span class="st">"gaussian"</span>,</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>                 <span class="at">adaptive=</span><span class="cn">TRUE</span>,</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>                 <span class="at">longlat=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/Snipaste_2024-11-11_12-34-41.png" class="img-fluid"></p>
<p>This output shows the cross-validation (CV) scores associated with different adaptive bandwidth values in a Geographically Weighted Regression (GWR) or a similar spatial model. Here’s how to interpret it:</p>
<ol type="1">
<li><p><strong>Adaptive Bandwidth Values</strong>: The bandwidth here represents the number of nearest neighbors considered in the localized models. Smaller bandwidths mean the model is more sensitive to local variations, while larger bandwidths make the model more global.</p></li>
<li><p><strong>CV Score</strong>: The CV score measures how well each bandwidth performs in cross-validation, with a lower score indicating better model performance. The score helps to balance model complexity and prediction accuracy, where lower values typically indicate a better fit to the data.</p></li>
<li><p><strong>Selecting the Optimal Bandwidth</strong>: From the list, you would typically select the bandwidth with the lowest CV score as the optimal choice. In this case, the bandwidth with a CV score of <code>20226641242</code> (appearing twice at bandwidths of 40) is the lowest observed. This suggests that a bandwidth of 40 may be the best option for balancing model accuracy and generalization.</p></li>
</ol>
<p>In summary, based on this output, you would likely choose an adaptive bandwidth of 40, as it yields the lowest CV score and therefore the best cross-validated performance for your model.</p>
<p>Let’s save the model output by using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(bw_adaptive, <span class="st">"data/HDB/rds/bw_adaptive.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code chunk below can be used to retrieve the save model in future.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>bw_adaptive <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/HDB/rds/bw_adaptive.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="constructing-the-adaptive-bandwidth-gwr-model" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="constructing-the-adaptive-bandwidth-gwr-model"><span class="header-section-number">3.4</span> Constructing the adaptive bandwidth gwr model</h3>
<p>Now, we can go ahead to calibrate the gwr-based hedonic pricing model by using adaptive bandwidth and Gaussian kernel as shown in the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>gwr_adaptive <span class="ot">&lt;-</span> <span class="fu">gwr.basic</span>(<span class="at">formula =</span> resale_price <span class="sc">~</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>                 floor_area_sqm <span class="sc">+</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>                 storey_avg <span class="sc">+</span> </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>                 remaining_lease_total_mths <span class="sc">+</span> </span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>                 proximity_to_mrt <span class="sc">+</span> </span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>                 proximity_to_goodprisch <span class="sc">+</span> </span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>                 within_1km_prisch <span class="sc">+</span> </span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>                 proximity_to_eldercare <span class="sc">+</span> </span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>                 proximity_to_CHAS <span class="sc">+</span> </span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>                 proximity_to_spmrkt <span class="sc">+</span> </span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>                 proximity_to_hawker <span class="sc">+</span> </span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>                 proximity_to_parks <span class="sc">+</span> </span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>                 proximity_to_childcare <span class="sc">+</span> </span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>                 within_350m_childcare <span class="sc">+</span> </span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>                 proximity_to_busstop <span class="sc">+</span> </span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>                 within_350m_busstop <span class="sc">+</span> </span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>                 proximity_to_mall,</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>                          <span class="at">data=</span>train_data_sp,</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>                          <span class="at">bw=</span>bw_adaptive, </span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>                          <span class="at">kernel =</span> <span class="st">'gaussian'</span>, </span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>                          <span class="at">adaptive=</span><span class="cn">TRUE</span>,</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>                          <span class="at">longlat =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code chunk below will be used to save the model in rds format for future use.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(gwr_adaptive, <span class="st">"data/HDB/rds/gwr_adaptive.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="retrieve-gwr-output-object" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="retrieve-gwr-output-object"><span class="header-section-number">3.5</span> Retrieve gwr output object</h3>
<p>The code chunk below will be used to retrieve the save gwr model object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>gwr_adaptive <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/HDB/rds/gwr_adaptive.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code below can be used to display the model output.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>gwr_adaptive</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   ***********************************************************************
   *                       Package   GWmodel                             *
   ***********************************************************************
   Program starts at: 2024-11-11 12:35:28.28084 
   Call:
   gwr.basic(formula = resale_price ~ floor_area_sqm + storey_avg + 
    remaining_lease_total_mths + proximity_to_mrt + proximity_to_goodprisch + 
    within_1km_prisch + proximity_to_eldercare + proximity_to_CHAS + 
    proximity_to_spmrkt + proximity_to_hawker + proximity_to_parks + 
    proximity_to_childcare + within_350m_childcare + proximity_to_busstop + 
    within_350m_busstop + proximity_to_mall, data = train_data_sp, 
    bw = bw_adaptive, kernel = "gaussian", adaptive = TRUE, longlat = FALSE)

   Dependent (y) variable:  resale_price
   Independent variables:  floor_area_sqm storey_avg remaining_lease_total_mths proximity_to_mrt proximity_to_goodprisch within_1km_prisch proximity_to_eldercare proximity_to_CHAS proximity_to_spmrkt proximity_to_hawker proximity_to_parks proximity_to_childcare within_350m_childcare proximity_to_busstop within_350m_busstop proximity_to_mall
   Number of data points: 53
   ***********************************************************************
   *                    Results of Global Regression                     *
   ***********************************************************************

   Call:
    lm(formula = formula, data = data)

   Residuals:
   Min     1Q Median     3Q    Max 
-27218  -8073   1380   9822  26935 

   Coefficients:
                              Estimate Std. Error t value Pr(&gt;|t|)  
   (Intercept)                209005.3   325770.2   0.642   0.5252  
   floor_area_sqm               3870.5     2328.8   1.662   0.1052  
   storey_avg                   1555.7      862.5   1.804   0.0797 .
   remaining_lease_total_mths   -171.1      356.8  -0.479   0.6345  
   proximity_to_mrt           -14587.2    26510.8  -0.550   0.5856  
   proximity_to_goodprisch     -2693.8    15598.5  -0.173   0.8639  
   within_1km_prisch            4097.2    15770.7   0.260   0.7965  
   proximity_to_eldercare       4951.2    19685.9   0.252   0.8029  
   proximity_to_CHAS          -15844.3    35057.6  -0.452   0.6540  
   proximity_to_spmrkt         -3048.0    34614.6  -0.088   0.9303  
   proximity_to_hawker         20348.1    15866.5   1.282   0.2079  
   proximity_to_parks          -9263.6    26084.5  -0.355   0.7246  
   proximity_to_childcare      -7379.6    51792.4  -0.142   0.8875  
   within_350m_childcare       -3804.8     3838.0  -0.991   0.3281  
   proximity_to_busstop        67798.6    59328.9   1.143   0.2607  
   within_350m_busstop          2185.8     1822.9   1.199   0.2383  
   proximity_to_mall           12992.6    35002.4   0.371   0.7127  

   ---Significance stars
   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 
   Residual standard error: 15640 on 36 degrees of freedom
   Multiple R-squared: 0.4686
   Adjusted R-squared: 0.2324 
   F-statistic: 1.984 on 16 and 36 DF,  p-value: 0.04377 
   ***Extra Diagnostic information
   Residual sum of squares: 8809680695
   Sigma(hat): 13143.01
   AIC:  1189.635
   AICc:  1209.753
   BIC:  1243.566
   ***********************************************************************
   *          Results of Geographically Weighted Regression              *
   ***********************************************************************

   *********************Model calibration information*********************
   Kernel function: gaussian 
   Adaptive bandwidth: 40 (number of nearest neighbours)
   Regression points: the same locations as observations are used.
   Distance metric: Euclidean distance metric is used.

   ****************Summary of GWR coefficient estimates:******************
                                    Min.    1st Qu.     Median    3rd Qu.
   Intercept                  103276.200 116917.878 125143.179 132045.986
   floor_area_sqm               3460.170   3909.214   4015.135   5258.983
   storey_avg                   1301.608   1377.038   1603.782   1646.507
   remaining_lease_total_mths   -305.807   -279.591   -109.236    -84.887
   proximity_to_mrt           -17544.314 -17128.293 -16636.057  -7304.776
   proximity_to_goodprisch     -3829.180  -2700.017  -2382.457   3204.890
   within_1km_prisch           -6157.607  -3737.040   4618.721   5608.667
   proximity_to_eldercare      -3544.639  -1753.441   3912.421   4406.509
   proximity_to_CHAS          -23946.423 -16486.447 -13718.926   4714.188
   proximity_to_spmrkt         -1459.413   2042.040   3747.888   4883.473
   proximity_to_hawker         17433.803  18666.208  20417.845  21040.997
   proximity_to_parks         -12673.527  -7283.971  -5557.734   1667.461
   proximity_to_childcare     -28332.788 -17460.966 -14701.844  32381.501
   within_350m_childcare       -5270.263  -3880.349  -3530.989    204.700
   proximity_to_busstop        60283.800  61431.791  79340.573  82077.784
   within_350m_busstop          1429.394   1528.051   2318.671   2371.214
   proximity_to_mall           12078.655  19120.249  20133.757  28929.507
                                   Max.
   Intercept                  218245.94
   floor_area_sqm               5539.89
   storey_avg                   1682.73
   remaining_lease_total_mths    -78.42
   proximity_to_mrt            -4834.40
   proximity_to_goodprisch      4408.98
   within_1km_prisch            7601.88
   proximity_to_eldercare       6276.63
   proximity_to_CHAS            6366.82
   proximity_to_spmrkt          6567.95
   proximity_to_hawker         21647.15
   proximity_to_parks           2647.07
   proximity_to_childcare      37758.05
   within_350m_childcare         767.48
   proximity_to_busstop        83640.86
   within_350m_busstop          2568.17
   proximity_to_mall           32001.73
   ************************Diagnostic information*************************
   Number of data points: 53 
   Effective number of parameters (2trace(S) - trace(S'S)): 21.21632 
   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 31.78368 
   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 1215.556 
   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 1166.083 
   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): 1170.997 
   Residual sum of squares: 7712357500 
   R-square value:  0.5348005 
   Adjusted R-square value:  0.2141817 

   ***********************************************************************
   Program stops at: 2024-11-11 12:35:28.291716 </code></pre>
</div>
</div>
</section>
<section id="converting-the-test-data-from-sf-data.frame-to-spatialpointdataframe" class="level3" data-number="3.6">
<h3 data-number="3.6" class="anchored" data-anchor-id="converting-the-test-data-from-sf-data.frame-to-spatialpointdataframe"><span class="header-section-number">3.6</span> Converting the test data from sf data.frame to SpatialPointDataFrame</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>test_data_sp <span class="ot">&lt;-</span> Wtest_data <span class="sc">%&gt;%</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_Spatial</span>()</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>test_data_sp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatialPointsDataFrame 
features    : 29 
extent      : 16206.33, 21512.98, 33696.28, 40886.84  (xmin, xmax, ymin, ymax)
crs         : +proj=tmerc +lat_0=1.36666666666667 +lon_0=103.833333333333 +k=1 +x_0=28001.642 +y_0=38744.572 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
variables   : 21
names       : resale_price,        town, region, flat_type, flat_model, floor_area_sqm, storey_avg, remaining_lease_total_mths, proximity_to_mrt, proximity_to_goodprisch, within_1km_prisch, proximity_to_eldercare,    proximity_to_CHAS,  proximity_to_spmrkt, proximity_to_hawker, ... 
min values  :       395000, Bukit Batok,   West,    4 ROOM, Simplified,             83,          2,                        733,  0.1168428466505,        1.06080581347727,                 0,      0.224055609298717, 1.94724087782615e-08, 7.13026183898598e-07,   0.176832997150221, ... 
max values  :       495000, Jurong West,   West,    4 ROOM, Simplified,             89,         11,                        777, 1.39680251695794,         5.3465481705808,                 0,       2.41846152812648,    0.479837420413484,     0.61067387833907,    2.08744917834828, ... </code></pre>
</div>
</div>
</section>
<section id="computing-predicted-values-of-the-test-data" class="level3" data-number="3.7">
<h3 data-number="3.7" class="anchored" data-anchor-id="computing-predicted-values-of-the-test-data"><span class="header-section-number">3.7</span> Computing predicted values of the test data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>gwr_pred <span class="ot">&lt;-</span> <span class="fu">gwr.predict</span>(<span class="at">formula =</span> resale_price <span class="sc">~</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>                 floor_area_sqm <span class="sc">+</span> </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                 storey_avg <span class="sc">+</span> </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                 remaining_lease_total_mths <span class="sc">+</span> </span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>                 proximity_to_mrt <span class="sc">+</span> </span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>                 proximity_to_goodprisch <span class="sc">+</span> </span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>                 within_1km_prisch <span class="sc">+</span> </span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>                 proximity_to_eldercare <span class="sc">+</span> </span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>                 proximity_to_CHAS <span class="sc">+</span> </span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>                 proximity_to_spmrkt <span class="sc">+</span> </span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>                 proximity_to_hawker <span class="sc">+</span> </span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>                 proximity_to_parks <span class="sc">+</span> </span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>                 proximity_to_childcare <span class="sc">+</span> </span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>                 within_350m_childcare <span class="sc">+</span> </span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>                 proximity_to_busstop <span class="sc">+</span> </span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>                 within_350m_busstop <span class="sc">+</span> </span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>                 proximity_to_mall,</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data=</span>train_data_sp, </span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>                        <span class="at">predictdata =</span> test_data_sp, </span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>                        <span class="at">bw=</span><span class="dv">40</span>, </span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a>                        <span class="at">kernel =</span> <span class="st">'gaussian'</span>, </span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>                        <span class="at">adaptive=</span><span class="cn">TRUE</span>, </span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>                        <span class="at">longlat =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code chunk below will be used to save the model in rds format for future use.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(gwr_pred, <span class="st">"data/HDB/rds/gwr_pred.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code chunk below will be used to retrieve the save gwr model object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>gwr_pred <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/HDB/rds/gwr_pred.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code below can be used to display the model output.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>gwr_pred</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   ***********************************************************************
   *                       Package   GWmodel                             *
   ***********************************************************************
   Program starts at: 2024-11-11 12:52:33.414486 
   Call:
   gwr.predict(formula = resale_price ~ floor_area_sqm + storey_avg + 
    remaining_lease_total_mths + proximity_to_mrt + proximity_to_goodprisch + 
    within_1km_prisch + proximity_to_eldercare + proximity_to_CHAS + 
    proximity_to_spmrkt + proximity_to_hawker + proximity_to_parks + 
    proximity_to_childcare + within_350m_childcare + proximity_to_busstop + 
    within_350m_busstop + proximity_to_mall, data = train_data_sp, 
    predictdata = test_data_sp, bw = 40, kernel = "gaussian", 
    adaptive = TRUE, longlat = FALSE)

   Dependent (y) variable for prediction:  resale_price
   Independent variables:  floor_area_sqm storey_avg remaining_lease_total_mths proximity_to_mrt proximity_to_goodprisch within_1km_prisch proximity_to_eldercare proximity_to_CHAS proximity_to_spmrkt proximity_to_hawker proximity_to_parks proximity_to_childcare within_350m_childcare proximity_to_busstop within_350m_busstop proximity_to_mall
   Number of data points: 53
   ***********************************************************************
   *     Results of Geographically Weighted Regression for prediction    *
   ***********************************************************************

   *********************Model calibration information*********************
   Kernel function: gaussian 
   Adaptive bandwidth: 40 (number of nearest neighbours)
   Distance metric: Euclidean distance metric is used.

   ****************Summary of GWR coefficient estimates:******************
                                         Min.    1st Qu.     Median    3rd Qu.
   Intercept_coef                   99921.875 106077.652 116574.187 132045.986
   floor_area_sqm_coef               3469.918   4027.749   4100.722   5095.451
   storey_avg_coef                   1308.402   1412.061   1608.985   1664.558
   remaining_lease_total_mths_coef   -303.040   -261.827   -101.184    -84.887
   proximity_to_mrt_coef           -17474.129 -17083.877 -16703.385  -9053.199
   proximity_to_goodprisch_coef     -3807.324  -2382.457  -2068.831   2232.594
   within_1km_prisch_coef           -5869.894  -2452.481   4342.919   5167.799
   proximity_to_eldercare_coef      -3312.198   -585.822   3730.485   4108.243
   proximity_to_CHAS_coef          -23914.949 -15799.882 -11973.248   2984.952
   proximity_to_spmrkt_coef         -1459.413   2764.910   3472.396   6292.418
   proximity_to_hawker_coef         17611.884  19414.352  20485.968  21427.543
   proximity_to_parks_coef         -12665.033  -6996.662  -4522.502    612.946
   proximity_to_childcare_coef     -28332.788 -14735.485 -10825.224  28915.454
   within_350m_childcare_coef       -5256.943  -3685.762  -3104.551   -290.356
   proximity_to_busstop_coef        60219.392  61557.090  79743.184  82612.147
   within_350m_busstop_coef          1443.124   1603.663   2249.168   2330.550
   proximity_to_mall_coef           12152.795  19532.661  21506.143  26254.662
                                         Max.
   Intercept_coef                  218226.957
   floor_area_sqm_coef               5513.990
   storey_avg_coef                   1682.731
   remaining_lease_total_mths_coef    -79.083
   proximity_to_mrt_coef            -5194.747
   proximity_to_goodprisch_coef      4240.686
   within_1km_prisch_coef            7601.878
   proximity_to_eldercare_coef       6233.049
   proximity_to_CHAS_coef            6059.762
   proximity_to_spmrkt_coef          6849.090
   proximity_to_hawker_coef         21647.147
   proximity_to_parks_coef           2172.947
   proximity_to_childcare_coef      37315.573
   within_350m_childcare_coef         681.334
   proximity_to_busstop_coef        83464.783
   within_350m_busstop_coef          2568.166
   proximity_to_mall_coef           31227.829

   ****************       Results of GW prediction       ******************
                       Min.   1st Qu.    Median   3rd Qu.      Max.
   prediction        413477    423653    438323    447092    479050
   prediction_var 305213908 332954204 356909371 401502262 664804873

   ***********************************************************************
   Program stops at: 2024-11-11 12:52:33.44649 </code></pre>
</div>
</div>
<p>Each row under the summary represents a predictor variable, with corresponding statistics for the estimated coefficients across locations:</p>
<ul>
<li><strong>Min, 1st Qu., Median, 3rd Qu., Max</strong>: These values show the distribution of coefficient estimates for each predictor variable across all locations. A wide range (difference between Min and Max) suggests substantial spatial variation in how a predictor influences <code>resale_price</code> in different areas.</li>
</ul>
<section id="interpretations" class="level4" data-number="3.7.1">
<h4 data-number="3.7.1" class="anchored" data-anchor-id="interpretations"><span class="header-section-number">3.7.1</span> Interpretations:</h4>
<ul>
<li><p><strong>floor_area_sqm_coef</strong>: The coefficient for <code>floor_area_sqm</code> has a range from approximately 4,027 to 5,513, indicating that each square meter of floor area affects resale price differently across locations. Higher coefficients in some areas imply that additional floor space increases resale price more significantly there.</p></li>
<li><p><strong>proximity_to_mrt_coef</strong>: The coefficient ranges from -17,474 to -1,608, meaning proximity to MRT (mass rapid transit) stations generally decreases resale price (negative impact). The wide range suggests that this impact is more substantial in some areas than others.</p></li>
<li><p><strong>proximity_to_hawker_coef</strong>: The coefficient for proximity to hawker centers has a range from approximately -28,355 to -14,625. This consistent negative impact across locations could suggest that proximity to hawker centers is generally not seen as favorable for resale prices, but the extent varies geographically.</p></li>
<li><p><strong>proximity_to_busstop_coef</strong>: The coefficients for proximity to bus stops have positive values ranging from 50.3 to 2,568. This indicates that being close to bus stops might have a small positive effect on resale prices, with stronger effects in certain locations.</p></li>
</ul>
<p>Generally, a wide range of coefficient values for a predictor implies significant spatial variation, meaning the predictor’s influence on <code>resale_price</code> depends heavily on location.</p>
</section>
<section id="results-of-gwr-prediction" class="level4" data-number="3.7.2">
<h4 data-number="3.7.2" class="anchored" data-anchor-id="results-of-gwr-prediction"><span class="header-section-number">3.7.2</span> Results of GWR Prediction</h4>
<ul>
<li><p><strong>Predicted Resale Prices</strong>:</p>
<ul>
<li><p><strong>Min</strong>: 305,213</p></li>
<li><p><strong>1st Quartile</strong>: 332,925</p></li>
<li><p><strong>Median</strong>: 435,699</p></li>
<li><p><strong>3rd Quartile</strong>: 498,332</p></li>
<li><p><strong>Max</strong>: 664,408</p></li>
</ul>
<p>These values represent the distribution of the predicted resale prices across all locations based on the GWR model. They give an idea of the range of resale prices in the dataset after considering spatial effects.</p></li>
</ul>
</section>
</section>
<section id="key-takeaways" class="level3" data-number="3.8">
<h3 data-number="3.8" class="anchored" data-anchor-id="key-takeaways"><span class="header-section-number">3.8</span> Key Takeaways</h3>
<ul>
<li><p><strong>Spatial Variation</strong>: The GWR model reveals that the impact of predictors on <code>resale_price</code> is not uniform across locations. This is particularly important for variables like <code>floor_area_sqm</code>, <code>proximity_to_mrt</code>, and <code>proximity_to_hawker</code>, which show significant variability in coefficients.</p></li>
<li><p><strong>Local Effects</strong>: GWR captures local effects better than a global model (like ordinary least squares) by adjusting the coefficients for each location, providing insights into how property characteristics affect resale prices differently across regions.</p></li>
<li><p><strong>Interpretation for Decision-Making</strong>: Real estate developers, urban planners, or policymakers could use this information to understand the varying influences of proximity to amenities or property features on housing prices and plan accordingly for different neighborhoods.</p></li>
</ul>
<p>This output suggests that the GWR model successfully captures the local variations in <code>resale_price</code>, making it a suitable approach for analyzing spatially heterogeneous data like property prices.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>